version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DEV_DATABASE_URI="postgresql+psycopg2://postgres:12345678@localhost:5432/gventas"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: gventas
    ports:
      - "5432:5432"
